image: milthorpe/comp1110-2021-s1-gitlab-ci:0.1.2

stages:
  - validate
  - build
  - test

before_script:
  - export PATH_TO_FX=/usr/share/openjfx/lib
  - export JAVAFX_OPTIONS="--module-path $PATH_TO_FX --add-modules=javafx.controls,javafx.fxml,javafx.media"
  - export CP=src:/labs/comp1110-labs.jar:/shared/junit-platform-console-standalone-1.7.0.jar
  - export JUNIT="java $JAVAFX_OPTIONS -jar /shared/junit-platform-console-standalone-1.7.0.jar --class-path $CP --disable-banner"

validate:
  tags:
    - comp1110
  stage: validate
  script:
    - python3 /checkintegrity.py Integrity.md /labs/Integrity.md ${GITLAB_USER_LOGIN} "${GITLAB_USER_NAME}"

build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding ISO-8859-1 $JAVAFX_OPTIONS -cp $CP src/comp1110/*/*.java
  artifacts:
    paths:
      - src/comp1110/*/*.class

lab1:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.lab1.HelloWorldTest
    - python3 /validate.py --exists src/comp1110/lab1/HelloTutor.png
  allow_failure: true

lab2:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.lab2.CountriesTest
    - $JUNIT -c=comp1110.lab2.ReverseTest
    - $JUNIT -c=comp1110.lab2.TriangleTest
  allow_failure: true

lab3:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.lab3.BucketTest
  allow_failure: true

lab4:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.lab4.HeadsOrTailsTest
  allow_failure: true

lab7:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.lab7.CropRotationTest
  allow_failure: true

lab8:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.lab8.ArrayStackTest
    - $JUNIT -c=comp1110.lab8.FamilyTreeTest
  allow_failure: true

## Local Variables:
## mode: yaml
## End:
